language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t arognstad/react-test -f  ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true arognstad/react-test npm test

after_success:
    - docker build -t arognstad/multi-client ./client
    - docker build -t arognstad/multi-nginx ./nginx
    - docker build -t arognstad/multi-server ./server
    - docker build -t arognstad/multi-worker ./worker
    # Login to docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
    # Push images to docker hub
    - docker push arognstad/multi-client
    - docker push arognstad/multi-nginx
    - docker push arognstad/multi-server
    - docker push arognstad/multi-worker