language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t arognstad/react-test -f  ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true arognstad/react-test npm test

after_success:
    - docker build -t arognstad/multi-client ./client
    - docker build -t arognstad/multi-nginx ./nginx
    - docker build -t arognstad/multi-server ./server
    - docker build -t arognstad/multi-worker ./worker
    # Login to docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
    # Push images to docker hub
    - docker push arognstad/multi-client
    - docker push arognstad/multi-nginx
    - docker push arognstad/multi-server
    - docker push arognstad/multi-worker

deploy:
    provider: elasticbeanstalk 
    edge: true
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-990026666207
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
        #secure: $AWS_SECRET_KEY